# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Blog di Antonio Trento"
description: > # this means to ignore newlines until "email:"
   Un naufrago del web approdato per condividere le sue conoscenze sul Web Marketing

email: lantoniotrento@gmail.com
#blog logo
logo: "/assets/images/antonio-trento-logo-android-chrome-512x512.png"
# blog cover
cover: "/assets/images/blog-background-mail.jpg"

name: 'Antonio Trento'
author: 'Antonio Trento'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://tonblog.github.io" # the base hostname & protocol for your site
baseurl: "/tonblog.github.io"
#used to display twitter cards
twitter_handle: '@officialtrento'

#fill in disqus shortname to use disqus
disqus: officialtrento

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/officialtrento
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/officialtrento
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/antoniotrento
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/+AntoniotrentoIt
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
